import type { Metadata } from 'next';
import { Sen, Nunito } from 'next/font/google';
import '@/styles/globals.scss';

const sen = Sen({
	variable: '--font-sen',
	subsets: ['latin'],
});

const nunito = Nunito({
	variable: '--font-nunito',
	subsets: ['latin'],
	// weight: ['400', '700', '800'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${sen.variable} ${nunito.variable}`}>{children}</body>
		</html>
	);
}
