import type { Metadata } from 'next';
import { Sen, Work_Sans } from 'next/font/google';
import '@/styles/globals.scss';

const sen = Sen({
	variable: '--font-sen',
	subsets: ['latin'],
});

const workSans = Work_Sans({
	variable: '--font-work-sans',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${sen.variable} ${workSans.variable}`}>{children}</body>
		</html>
	);
}
